from enum import Enum

class Aid(Enum):
    AUXILIO_EMERGENCIAL = "EMERGENCIAL"
    AUXILIO_ALIMENTACAO_RESIDENCIA = "RESIDÊNCIA"
    AUXILIO_ALIMENTACAO = "ALIMENTAÇÃO"
    AUXILIO_MORADIA = "MORADIA"
    AUXILIO_RESIDENCIA_RUMF = "RUMF"
    AUXILIO_RESIDENCIA_RUFET = "RUFET"
    AUXILIO_RESIDENTES = "RESIDENTES"
    AUXILIO_EMERGENCIAL_COMPLEMENTAR = "ALIMENTAÇÃO COMPLEMENTAR"
    AUXILIO_CRECHE = "PRÉ-ESCOLAR"
    AUXILIO_TRANSPORTE = "TRANSPORTE"
    AUXILIO_TRANSPORTE_FAIXA_I = "(FAIXA I)"
    AUXILIO_TRANSPORTE_FAIXA_II = "(FAIXA II)"
    AUXILIO_TRANSPORTE_FAIXA_III = "(FAIXA III)"